name: Bug report
description: File a reproducible bug report
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Clear, reproducible description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Include minimal code and input data shape.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Yggdrasil version
      placeholder: 0.0.1
